### ISSUE TITLE
Make a page implementing material design as a demonstration 

### ISSUE THREAD

**Issue by samschurter** [MakeICT/MESSforMakers#24]
need not be based on the wireframes

**Comment by tomscholz** [comment]
I would like to work on this, but I would need some more information on how to run the app locally

**Comment by samschurter** [comment]
cool, thanks! I'm out of town right now, but I should be able to help tomorrow. It you might be able yo find help on the DevICT slack channel. check the readme for the invite link

**Comment by samschurter** [comment]
@tomscholz I created a new branch, material-design-demo, and updated the readme there https://github.com/MakeICT/MESSforMakers/tree/material-design-demo .  There's a MESSforMakers channel on the devICT Slack if you need more help https://devict-slackin.herokuapp.com/

**Comment by samschurter** [comment]
Closed with #60
