### ISSUE TITLE
Design the routes for the app

### ISSUE THREAD

**Issue by samschurter** [MakeICT/MESSforMakers#30]

**Comment by duckoder** [comment]
@SkippOtter hello, I can help you with this. Can you give more details, what you want to do in this issue ?

**Comment by samschurter** [comment]
thanks!  If you check out the readme, there's a link to NinjaMock that has the website wireframes, and that's a good place to start.  It's not complete though, for example I don't think it has any example of login/logout.  so we need something like the following:

unregistered users can
- view list of events
- view event details
- register for an account

registered users can
- log in
- log out
- enroll in event
- cancel event
- view personal profile
- edit personal profile

administrator can
- CRUD equipment (Create, Read, Update, Delete)
- CRUD areas
- CRUD events
- list users

this is a very incomplete list but it should be a start.  I think the important thing is to make it readable and easy to add more routes

**Comment by samschurter** [comment]
also, joining our slack channel is a good idea if you need more info, too.  it's easier to talk there, and there's more people.  I'm pretty new to this and there's people with a lot more experience than me that can answer questions better, too

**Comment by samschurter** [comment]
closed with #59
