### ISSUE TITLE
README Edit

### ISSUE THREAD

**Issue by jcox250** [MakeICT/MESSforMakers#45]
Hi I made an edit to the READMe to remove the following code indent
<img width="1071" alt="screen shot 2017-10-01 at 09 33 00" src="https://user-images.githubusercontent.com/16992818/31053179-5c95ecb6-a68f-11e7-8d5a-442c2563ee34.png">

So that this section of the README is now more readable.

<img width="1105" alt="screen shot 2017-10-01 at 09 44 14" src="https://user-images.githubusercontent.com/16992818/31053181-68dbe1ec-a68f-11e7-9365-3ce3a974dd4d.png">

I forked the repo and made my change on the edit-readme branch. However, the README on the edit-readme branch is nowhere near as up to date as the README on the master branch. I don't want to make the pull request from my branch to the master but I'm also not sure if I should make the pull request to the edit-readme branch as the diff will make it look like I've done more than I have.

This is my first time making a pull request so any help would be appreciated.

**Comment by samschurter** [comment]
I'm pretty new to using Github too,  so bear with me.

The edit-readme is an old edit branch that needs to be deleted. I've got some readme edits to add as well, so I think the best would be to create a new branch something like edit-readme2.  Then you can make your changes and commit, I'll make my changes and commit, then you can submit the pull request

**Comment by jcox250** [comment]
Would you be able to make the edit-readme2 branch and then I can make my commits and submit my pull request? I don't have permissions on this repo to make a new branch but once the edit-readme2 branch has been made I can fork the repo, make my changes and then submit my pull request.

**Comment by samschurter** [comment]
@jcox250 I added you as a collaborator, see if you can create a branch now

**Comment by jcox250** [comment]
@SkippOtter I tried pushing a local edit-readme branch to the repo but got the following error.
<img width="759" alt="screen shot 2017-10-02 at 19 30 42" src="https://user-images.githubusercontent.com/16992818/31093276-1db278a0-a7a9-11e7-94cb-2e13d6143f8f.png">

I also tried creating a new branch on the repo by clicking on the branch dropdown and typing in the branch name (see image below) which is something I can do on my own repos which makes me think there may still be some sort of permissions error? Or I may be doing something completely wrong?

<img width="455" alt="screen shot 2017-10-02 at 19 41 29" src="https://user-images.githubusercontent.com/16992818/31093459-b5bf3232-a7a9-11e7-96c1-28b267c062a7.png">

**Comment by samschurter** [comment]
ok, I went ahead and just created the new branch.  I'll read up on repo permissions when I get a chance to avoid this in the future.

**Comment by jcox250** [comment]
@SkippOtter Just checked my emails and saw an invite to be a collaborator and I just accepted the invite. I have a feeling this is what the issue was. Apologies about this. I'll make my changes and submit my pull request asap.

**Comment by samschurter** [comment]
no worries, I'm just learning project management as I go here
