### ISSUE TITLE
add config options

### ISSUE THREAD

**Issue by samschurter** [MakeICT/MESSforMakers#50]
Need to read config options from a JSON file and store in a struct in the application struct.  The file should look something like this to start:

{
	"database_settings": {
		"username":"",
		"password":"",
		"host":"",
		"port":"",
		"database":"",
		"sslmode":""
	},
	"logger_settings": {
		"dump_request":""
	}
}

This config.json file should be added to .gitignore to prevent sharing credentials

**Comment by duckoder** [comment]
@SkippOtter hello, I can help you with this

**Comment by duckoder** [comment]
@SkippOtter as I see, there is no logic for connect to the database, right ? This config stuff it's for future

**Comment by samschurter** [comment]
@zhikiri the connect code is currently in branch database-model and PR #49.  There are a few minor changes to make on that pull request, but if you branch from database-model you should be pretty close

**Comment by duckoder** [comment]
@SkippOtter ou, okay. So I'll base my branch on `database-model` one

**Comment by duckoder** [comment]
@SkippOtter here is the PR https://github.com/MakeICT/MESSforMakers/pull/52, it's currently in progress (left just put usage of config parser)

**Comment by samschurter** [comment]
@zhikiri ok, probably for the best cuz there's some fiddling to do with the DB in the other branch.

**Comment by duckoder** [comment]
@SkippOtter sorry, I didn't get it :) Can explain in details ?

**Comment by samschurter** [comment]
it's good that you left out the usage of the config parser, because some changes I need to make to the `database-model` branch that might cause merge conflicts

**Comment by duckoder** [comment]
@SkippOtter emm... I've just add usage of it for database connection setup :(

**Comment by samschurter** [comment]
haha, that's fine, too. your PR has been approved, so I'll merge it back in before I continue working. shouldn't be a problem :ok_hand:

**Comment by samschurter** [comment]
fixed with PR #52
